ERROR - 2024-08-21 08:11:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-21 08:11:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `status`, `email`, `password`) VALUES (:nombre:, :apellido:, :telefono:, :status:, :email:, :password:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-21 08:12:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-21 08:12:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `status`, `email`, `password`) VALUES (:nombre:, :apellido:, :telefono:, :status:, :email:, :password:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-21 08:16:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-21 08:16:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `status`, `email`, `password`) VALUES (:nombre:, :apellido:, :telefono:, :status:, :email:, :password:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-21 08:18:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-21 08:18:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `status`, `email`, `password`) VALUES (:nombre:, :apellido:, :telefono:, :status:, :email:, :password:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-21 08:19:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-21 08:19:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `status`, `email`, `password`) VALUES (:nombre:, :apellido:, :telefono:, :status:, :email:, :password:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-21 08:24:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-21 08:24:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `email`, `password`, `status`) VALUES (:nombre:, :apellido:, :telefono:, :email:, :password:, :status:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-21 08:27:40 --> ErrorException: Array to string conversion
[Method: POST, Route: guardar]
in APPPATH\Controllers\UsuarioController.php on line 72.
 1 APPPATH\Controllers\UsuarioController.php(72): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\xampp\\htdocs\\personalizacionSis\\app\\Controllers\\UsuarioController.php', 72)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-21 08:33:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-21 08:33:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `email`, `password`, `status`) VALUES (:nombre:, :apellido:, :telefono:, :email:, :password:, :status:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(61): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-21 08:40:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\personalizacionSis\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\personalizacionSis\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\personalizacionSis\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\personalizacionSis\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\personalizacionSis\app\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\personalizacionSis\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\personalizacionSis\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\personalizacionSis\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\personalizacionSis\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-21 08:40:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `email`, `password`, `status`) VALUES (:nombre:, :apellido:, :telefono:, :email:, :password:, :status:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
